app:
    resource: '@AppBundle/Controller/'
    type: annotation

# redirecting the root
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /movies
        permanent: true
